### ISSUE TITLE
Search by tags

### ISSUE THREAD

**Issue by homoky** [nicolaslopezj/searchable#36]
Hi.

I look for this great package. Is there any community forum for this project?

I would like to ask if there is to possibility to search with tags. Structure:

posts:
- id

post_tag:
- post_id
- tag_id

tags:
- id
- title

Thanks

**Comment by nicolaslopezj** [comment]
You can search with joins

**Comment by alinf** [comment]
Hello,

I have a model Release with:

 protected $searchable = [
        'columns' => [
            'releases.title' => 10,
            'content' => 8,
            'tags.title' => 1
        ],
        'joins' => [
            'releases_tags' => ['releases.id', 'releases_tags.release_id'],
            'tags' => ['releases_tags.tag_id', 'tags.id']
        ]
    ];

Relationship:
public function tags(){
	return $this->belongsToMany('Tag', 'releases_tags')->withTimestamps();
}

Structure is:
releases - id, title, content
releases_tags - id, release_id, tag_id
tags - id, title

The result are being repeated because it groups by `tags.title`. If it only groups by `releases`.`id`, everything is ok. What sould I do?
Thanks in advance!

**Comment by nicolaslopezj** [comment]
@Evertt could you help here?

**Comment by alinf** [comment]
Well, if i add another groupBy like this

$results = FacebookPost::where('users_facebook_posts.organisation_id', $organisation_id)
            ->search($query)
            ->groupBy('users_facebook_posts.id')
            ->with(['users', 'tags', 'pages']);

it seems to work as expected

**Comment by nicolaslopezj** [comment]
Thats great
