### ISSUE TITLE
Strange behavior when searching with joins

### ISSUE THREAD

**Issue by iget-master** [nicolaslopezj/searchable#66]
Hi,

I've the following search configured at my `HotelRoom` model.

```
    /**
     * Searchable rules.
     *
     * @var array
     */
    protected $searchable = [
        'columns' => [
            'name' => 10,
            'hotels.invented_name' => 10,
            'hotels.company_name' => 10,
            'location_cities.full_name' => 10,
        ],
        'joins' => [
            'hotels' => ['hotel_rooms.hotel_id', 'hotels.id'],
            'location_cities' => ['hotels.location_city_id', 'location_cities.ufi'],
        ]
    ];
```

And I have an HotelRoom with the name `Cristal test`

If I do a search for `cristal`, it results correctly.
But if I do a search for `test`, it don't results anything.

Then I tried to remove my joins:

```
    /**
     * Searchable rules.
     *
     * @var array
     */
    protected $searchable = [
        'columns' => [
            'name' => 10,
        ],
        'joins' => [
        ]
    ];
```

And noticed that the search works perfectly, resulting both for `cristal` or `test`

What may be happening here?

**Comment by iget-master** [comment]
Hello? Is this abandoned?

**Comment by jarektkaczyk** [comment]
Try this https://github.com/jarektkaczyk/eloquence/wiki/Builder-searchable-and-more#searchable

**Comment by saurabh-pathak94** [comment]
Same issue dude.  And @jarektkaczyk stop advertising on every issue.

**Comment by jarektkaczyk** [comment]
@saurabh-pathak94 Why don't you find the issue, fix it and send a PR rather than duplicating same issue and worthless comments?

**Comment by saurabh-pathak94** [comment]
@jarektkaczyk dude we are trying to get this one working. Anyone can Google up and see other packages. So stop littering every damn issue OK? We all looked at all the present issues and frankly I found your ads more than actual solutions. Anyhow, happy advertising! 
P. S.  Don't get so sensitive. ☺

**Comment by jarektkaczyk** [comment]
@iget-master It has nothing to do with `joins`, but the relevance score. In your case you need more than `4 * 10 / 4 = 10` for a result to show up. Unfortunately last case, that is `'%term%'`, gives a row score **10**, while `'term%'` **50**.

That said, that's not some code issue, but, say, coincidence. I you had different weights for the columns, or eg. 3 instead of 4 cols with weight `10`, then it would work as expected.

Test it out - run `HotelRoom::search('test', 1)->get()` (or anything below 10) in order to override the threshold, and you'll get your row.


@saurabh-pathak94 Apparently you're having hard time trying! But you're funny guy, so let me help you out this time. And frankly, this is the first actual solution I'm giving, all the solutions to pretty much every issue here I already provided in the package of mine instead. You can't squeeze blood out of a turnip...

**Comment by saurabh-pathak94** [comment]
@jarektkaczyk see now the answer you gave, you should have given that.  This was helpful. Thank you.  And jeez, relax. Lol.

**Comment by iget-master** [comment]
@nicolaslopezj Please take a look at #125, it solves this issue!
